server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver  #org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:33306/db2021?useUnicode=true&charactorEncoding=utf-8&useSSL=false
    username: junyi
    password: 23456789

mybatis:
  mapperLocations: classpass:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities   #

eureka:
  instance:
    hostname: localhost   #eureka 服务实例名
    port: 7001
  client:
    register-with-eureka: true   # false表示不向注册中心注册自己
    fetch-register: true         # false 表示自己不进行检索，因为在积极就是注册中心
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/    # 设置与eureka server交互的地址，查询和注册都是用这个信息