server:
  port: ${server_port:7001}

eureka:
  instance:
    hostname: ${instance_host:localhost}   #eureka 服务实例名
  register:
    hostname: ${register_host:localhost}   #eureka 集群模式使用的注册域名
  client:
    register-with-eureka: false   # false表示不向注册中心注册自己
    fetch-register: false         # false 表示自己不进行检索，因为在积极就是注册中心
    service-url:
      defaultZone: http://${eureka.register.hostname}/eureka/    # 设置与eureka server交互的地址，查询和注册都是用这个信息
  server:
    enable-self-preservation: ${self_preserve:false} # 设为false，关闭自我保护
    #eviction-interval-timer-in-ms: 4000 # 清理间隔（单位毫秒，默认是60*1000）